default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Settings.db.host %>
  username: <%= Settings.db.user %>
  password: <%= Settings.db.password %>
  pool: <%= Settings.db.pool %>

development:
  primary:
    <<: *default
    database: taptap_development

test:
  primary:
    <<: *default
    database: taptap_test

production:
  primary:
    <<: *default
    database: taptap_production
